In [22]:
# Concatenateing program with flip and axis function
import numpy as np
# declaration of array 
arr1=np.array([[2,5],[6,8]])
arr2=np.array([[9,11],[16,18]])
# concatenateing
con=np.concatenate((arr1,arr2),axis=1)
y=np.concatenate((arr1,arr2),axis=0)
reverse=(np.flip(arr1))
print("concatenateing of two arrays")
print(con)
print("\n reverse of data")
print(reverse)
print("\n axis of the data")
print(y)

concatenateing of two arrays
[[ 2  5  9 11]
 [ 6  8 16 18]]

 reverse of data
[[8 6]
 [5 2]]

 axis of the data
[[ 2  5]
 [ 6  8]
 [ 9 11]
 [16 18]]
